apt-get remove acccheck
apt-get remove ace-voip
apt-get remove amap
apt-get remove automater
apt-get remove bing-ip2hosts
apt-get remove braa
apt-get remove casefile
apt-get remove cdpsnarf
apt-get remove cisco-torch
apt-get remove cookie
apt-get remove copy-router-config
apt-get remove dmitry
apt-get remove dnmap
apt-get remove dnsenum
apt-get remove dnsmap
apt-get remove dnsrecon
apt-get remove dnstracer
apt-get remove dnswalk
apt-get remove dotdotpwn
apt-get remove enum4linux
apt-get remove enumiax
apt-get remove exploitdb
apt-get remove fierce
apt-get remove firewalk
apt-get remove fragroute
apt-get remove fragrouter
apt-get remove ghost
apt-get remove golismero
apt-get remove goofile
apt-get remove hping3
apt-get remove intrace
apt-get remove ismtp
apt-get remove lbd
apt-get remove maltego
apt-get remove masscan
apt-get remove metagoofil
apt-get remove miranda
apt-get remove nmap
apt-get remove ntop
apt-get remove p0f
apt-get remove parsero
apt-get remove recon-ng
apt-get remove set
apt-get remove smtp-user-enum
apt-get remove snmpcheck
apt-get remove sslcaudit
apt-get remove sslsplit
apt-get remove sslstrip
apt-get remove sslyze
apt-get remove thc-ipv6
apt-get remove theharvester
apt-get remove tlssled
apt-get remove twofi
apt-get remove urlcrazy
apt-get remove wireshark
apt-get remove wol-e
apt-get remove xplico
apt-get remove bbqsql
apt-get remove bed
apt-get remove cisco-auditing-tool
apt-get remove cisco-global-exploiter
apt-get remove cisco-ocs
apt-get remove cisco-torch
apt-get remove copy-router-config
apt-get remove dbpwaudit
apt-get remove doona
apt-get remove dotdotpwn
apt-get remove greenbone
apt-get remove gsd
apt-get remove hexorbase
apt-get remove inguma
apt-get remove jsql
apt-get remove lynis
apt-get remove nmap
apt-get remove ohrwurm
apt-get remove openvas-administrator
apt-get remove openvas-cli
apt-get remove openvas-manager
apt-get remove openvas-scanner
apt-get remove oscanner
apt-get remove powerfuzzer
apt-get remove sfuzz
apt-get remove sidguesser
apt-get remove siparmyknife
apt-get remove sqlmap
apt-get remove sqlninja
apt-get remove sqlsus
apt-get remove thc-ipv6
apt-get remove tnscmd10g
apt-get remove unix-privesc-check
apt-get remove yersinia
apt-get remove aircrack-ng
apt-get remove asleap
apt-get remove bluelog
apt-get remove bluemaho
apt-get remove bluepot
apt-get remove blueranger
apt-get remove bluesnarfer
apt-get remove bully
apt-get remove cowpatty
apt-get remove crackle
apt-get remove eapmd5pass
apt-get remove fern
apt-get remove ghost
apt-get remove giskismet
apt-get remove gqrx
apt-get remove gr-scan
apt-get remove kalibrate-rtl
apt-get remove killerbee
apt-get remove kismet
apt-get remove mdk3
apt-get remove mfcuk
apt-get remove mfoc
apt-get remove mfterm
apt-get remove multimon-ng
apt-get remove pixiewps
apt-get remove reaver
apt-get remove redfang
apt-get remove rtlsdr
apt-get remove spooftooph
apt-get remove wifi
apt-get remove wifitap
apt-get remove wifite
apt-get remove apache-users
apt-get remove arachni
apt-get remove bbqsql
apt-get remove blindelephant
apt-get remove burp
apt-get remove cutycapt
apt-get remove davtest
apt-get remove deblaze
apt-get remove dirb
apt-get remove dirbuster
apt-get remove fimap
apt-get remove funkload
apt-get remove grabber
apt-get remove jboss-autopwn
apt-get remove joomscan
apt-get remove jsql
apt-get remove maltego
apt-get remove padbuster
apt-get remove paros
apt-get remove parsero
apt-get remove plecost
apt-get remove powerfuzzer
apt-get remove proxystrike
apt-get remove recon-ng
apt-get remove skipfish
apt-get remove sqlmap
apt-get remove sqlninja
apt-get remove sqlsus
apt-get remove ua-tester
apt-get remove uniscan
apt-get remove vega
apt-get remove w3af
apt-get remove webscarab
apt-get remove webshag
apt-get remove webslayer
apt-get remove websploit
apt-get remove wfuzz
apt-get remove wpscan
apt-get remove xsser
apt-get remove zaproxy
apt-get remove armitage
apt-get remove backdoor
apt-get remove beef
apt-get remove cisco-auditing-tool
apt-get remove cisco-global-exploiter
apt-get remove cisco-ocs
apt-get remove cisco-torch
apt-get remove commix
apt-get remove crackle
apt-get remove jboss-autopwn
apt-get remove linux
apt-get remove maltego
apt-get remove set
apt-get remove shellnoob
apt-get remove sqlmap
apt-get remove thc-ipv6
apt-get remove yersinia
apt-get remove binwalk
apt-get remove bulk-extractor
apt-get remove capstone
apt-get remove chntpw
apt-get remove cuckoo
apt-get remove dc3dd
apt-get remove ddrescue
apt-get remove dff
apt-get remove distorm3
apt-get remove dumpzilla
apt-get remove extundelete
apt-get remove foremost
apt-get remove galleta
apt-get remove guymager
apt-get remove iphone
apt-get remove p0f
apt-get remove pdf-parser
apt-get remove pdfid
apt-get remove pdgmail
apt-get remove peepdf
apt-get remove regripper
apt-get remove volatility
apt-get remove xplico
apt-get remove dhcpig
apt-get remove funkload
apt-get remove iaxflood
apt-get remove inundator
apt-get remove inviteflood
apt-get remove ipv6-toolkit
apt-get remove mdk3
apt-get remove reaver
apt-get remove rtpflood
apt-get remove slowhttptest
apt-get remove t50
apt-get remove termineter
apt-get remove thc-ipv6
apt-get remove thc-ssl-dos
apt-get remove burp
apt-get remove dnschef
apt-get remove fiked
apt-get remove hamster-sidejack
apt-get remove hexinject
apt-get remove iaxflood
apt-get remove inviteflood
apt-get remove ismtp
apt-get remove isr-evilgrade
apt-get remove mitmproxy
apt-get remove ohrwurm
apt-get remove protos-sip
apt-get remove rebind
apt-get remove responder
apt-get remove rtpbreak
apt-get remove rtpinsertsound
apt-get remove rtpmixsound
apt-get remove sctpscan
apt-get remove siparmyknife
apt-get remove sipp
apt-get remove sipvicious
apt-get remove sniffjoke
apt-get remove sslsplit
apt-get remove sslstrip
apt-get remove thc-ipv6
apt-get remove voiphopper
apt-get remove webscarab
apt-get remove wifi
apt-get remove wireshark
apt-get remove xspy
apt-get remove yersinia
apt-get remove zaproxy
apt-get remove maskprocessor
apt-get remove multiforcer
apt-get remove ncrack
apt-get remove oclgausscrack
apt-get remove pack
apt-get remove patator
apt-get remove phrasendrescher
apt-get remove polenum
apt-get remove rainbowcrack
apt-get remove rcracki-mt
apt-get remove rsmangler
apt-get remove sqldict
apt-get remove statsprocessor
apt-get remove thc-pptp-bruter
apt-get remove truecrack
apt-get remove webscarab
apt-get remove wordlists
apt-get remove zaproxy
apt-get remove cryptcat
apt-get remove cymothoa
apt-get remove dbd
apt-get remove dns2tcp
apt-get remove http-tunnel
apt-get remove httptunnel
apt-get remove intersect
apt-get remove nishang
apt-get remove polenum
apt-get remove powersploit
apt-get remove pwnat
apt-get remove ridenum
apt-get remove sbd
apt-get remove u3-pwn
apt-get remove webshells
apt-get remove weevely
apt-get remove winexe
apt-get remove android-sdk
apt-get remove apktool
apt-get remove arduino
apt-get remove dex2jar
apt-get remove sakis3g
apt-get remove apktool
apt-get remove dex2jar
apt-get remove distorm3
apt-get remove edb-debugger
apt-get remove jad
apt-get remove javasnoop
apt-get remove jd-gui
apt-get remove ollydbg
apt-get remove smali
apt-get remove valgrind
apt-get remove yara
apt-get remove casefile
apt-get remove cutycapt
apt-get remove dos2unix
apt-get remove dradis
apt-get remove keepnote
apt-get remove magictree
apt-get remove metagoofil
apt-get remove nipper-ng
apt-get remove pipal

